site_name: FiveOrbs Route
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
	name: fiveorbs
repo_url: https://github.com/fiveorbs/route
extra:
	project: Route
plugins:
	- search
	- macros:
		module_name: docs/main
